name: Pull Request

env:
  SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
  SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
  REDIRECT_URI: http://localhost:8080/callback

on: pull_request

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.1"

      - name: Formate
        run: go fmt
